language: node_js
node_js:
    - node
before_install:
    - echo "VUE_APP_BASEAPI='${VUE_APP_BASEAPI}'" > .env.production
install:
    - yarn install
script:
    - yarn build
after_success:
    - tar -zcvf vue-shop-${TRAVIS_TAG}.zip dist
deploy:
    provider: releases
    api_key: ${GITHUB_OAUTH_TOKEN}
    file: vue-shop-${TRAVIS_TAG}.zip
    skip_cleanup: true
    on:
        tags: true
