language: node_js
node_js:
    - node
install:
    - yarn install
script:
    - yarn build
after_success:
    - tar -zcvf dist vue-shop-${TRAVIS_BUILD_NUMBER}.zip
deploy:
    provider: releases
    api_key: ${GITHUB_OAUTH_TOKEN}
    file: vue-shop-${TRAVIS_BUILD_NUMBER}.zip
    skip_cleanup: true
    on:
        tags: true
