export default {
    /* COMPONENT */
    ALERT_MESSAGE: 'ALERT_MESSAGE',
    START_LOADING: 'START_LOADING',
    FINISH_LOADING: 'FINISH_LOADING',

    /* USER */
    USER_TOKEN: 'USER_TOKEN',
    USER_LOGIN: 'USER_LOGIN',
    USER_REGISTER: 'USER_REGISTER',
    USER_LOGOUT: 'USER_LOGOUT',
    USER_PROFILE: 'USER_PROFILE',

    /* PRODUCTS */
    PRODUC_LIST_LOAD: 'PRODUC_LIST_LOAD',
    PRODUCT_LOAD: 'PRODUCT_LOAD',

    /* SHOPPING_CART */
    CART_UPDATE: 'CART_CHANGE',
    CART_REMOVE: 'CART_REMOVE',
    CART_ADD: 'CART_ADD',
};
